import React from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';

const projects = [
  { n:'01', title:'MH Mega Mall', type:'Frontend / E-Commerce', text:'A multi-category storefront for electronics, groceries, and fashion, focused on clear browsing and responsive layouts.', tech:'HTML5 · CSS3', live:'https://hussain-hakimi.github.io/SEMESTER-1-PROJECT/', repo:'https://github.com/Hussain-Hakimi/SEMESTER-1-PROJECT' },
  { n:'02', title:'Developer Portfolio', type:'Frontend / Personal Brand', text:'A personal portfolio built to present my work, learning journey, and contact information in a straightforward way.', tech:'HTML5 · CSS Grid', live:'https://hussainhakimi.netlify.app/', repo:'https://github.com/Hussain-Hakimi' },
  { n:'03', title:'Road Accident Dashboard', type:'Data Analytics', text:'An Excel dashboard using pivot tables, formulas, and slicers to explore accident severity, causes, and trends.', tech:'Microsoft Excel · Data Analysis', repo:'https://github.com/Hussain-Hakimi/Road_Accident-Dashboard/blob/main/README.md' }
];
const skills = { Languages:['C#','JavaScript','Python','SQL','HTML','CSS'], Database:['SQL Server'], Tools:['Git','GitHub','Visual Studio','VS Code','Excel'], Focus:['Excel Specialist','Power BI'] };
function App(){return <div className="page">
<header><a className="logo" href="#top">HH<span>.</span></a><nav><a href="#work">Work</a><a href="#about">About</a><a href="#skills">Skills</a><a href="#contact">Contact</a></nav><a className="header-cta" href="mailto:hussain.hakimi216@gmail.com">Let’s talk ↗</a></header>
<main id="top">
<section className="hero"><div className="hero-grid"></div><div className="hero-content"><p className="eyebrow">Software Engineering · UET Lahore · 2025—2029</p><h1>Hussain<br/><i>Hakimi.</i></h1><p className="lead">Software Engineering student and frontend developer building responsive web applications, relational databases, and data-driven solutions while growing into backend and full-stack engineering.</p><div className="actions"><a className="primary" href="#work">Explore my work <span>↓</span></a><a className="secondary" href="https://github.com/Hussain-Hakimi" target="_blank">GitHub ↗</a></div></div><div className="hero-side"><span>01</span><p>BUILD<br/>LEARN<br/>IMPROVE</p></div></section>
<section id="work" className="work"><div className="section-top"><p className="eyebrow">Selected work</p><h2>Things I’ve<br/><i>built so far.</i></h2><p className="section-note">Three projects from my journey across frontend development and data analytics.</p></div><div className="project-list">{projects.map(p=><article className="project" key={p.n}><div className="project-num">{p.n}</div><div><p className="project-type">{p.type}</p><h3>{p.title}</h3><p className="project-text">{p.text}</p><p className="tech">{p.tech}</p><div className="links">{p.live&&<a href={p.live} target="_blank">Live demo ↗</a>}<a href={p.repo} target="_blank">GitHub ↗</a></div></div><div className="project-arrow">↗</div></article>)}</div></section>
<section id="about" className="about"><div><p className="eyebrow">About me</p><h2>From business<br/>to <i>building software.</i></h2></div><div className="about-copy"><p>I did not start out in software. I first studied Business Administration, then found that I enjoyed solving problems with code much more.</p><p>I am now studying Software Engineering at UET Lahore, where I am learning frontend development, databases, and data analysis. I like building something useful, finding what is not working, and making it better.</p><p>Right now, I am working toward becoming a dependable full-stack developer.</p><div className="facts"><div><strong>03+</strong><span>Featured builds</span></div><div><strong>06</strong><span>Core languages</span></div><div><strong>2029</strong><span>Expected graduation</span></div></div></div></section>
<section id="skills" className="skills"><div className="section-top"><p className="eyebrow">Toolkit</p><h2>What I’m<br/><i>working with.</i></h2></div><div className="skill-grid">{Object.entries(skills).map(([k,v],i)=><div className="skill" key={k}><span>0{i+1}</span><h3>{k}</h3><div>{v.map(x=><b key={x}>{x}</b>)}</div></div>)}</div><div className="experience"><div><p className="eyebrow">Experience</p><h3>Volunteer Instructor</h3><p className="muted">Winter Courses & School Programs · 3 years</p></div><p>During three winter breaks, I taught school students with Hassan Hakimi and Mohammad Hussain. It taught me how to explain ideas clearly and stay patient when someone needs more time.</p></div><div className="education"><p className="eyebrow">Education</p><h3>Bachelor of Software Engineering</h3><p>University of Engineering & Technology (UET), Lahore</p><span>2025 — 2029</span></div></section>
<section id="contact" className="contact"><p className="eyebrow">Let’s connect</p><h2>Have an idea?<br/><i>Let’s build it.</i></h2><a className="email" href="mailto:hussain.hakimi216@gmail.com">hussain.hakimi216@gmail.com <span>↗</span></a><div className="socials"><a href="https://github.com/Hussain-Hakimi" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/hussain-hakimi/" target="_blank">LinkedIn ↗</a><a href="https://hussain-blog.netlify.app/" target="_blank">Blog ↗</a></div></section>
</main><footer><span>Hussain Hakimi © 2026</span><span>Designed & built with intention.</span></footer></div>}
createRoot(document.getElementById('root')).render(<App />);
